### ISSUE TITLE
Caching initial server rendered response

### ISSUE THREAD

**Issue by TroodoNmike** [evertonrobertoauler/cli-universal-demo#10]
Great repo, minimal setup. Love it.

I am interested in finding a way to cache initial server response when there are ajax calls (via angular http). At the moment when client lands on the page any ajax calls have to be requested again (one call on the server, then one on the client).

I remember angular universal team had embedded json string into the source code and thats how they managed that. I wonder if there is another way we could do it? Any thoughts?

**Comment by NKjoep** [comment]
can this be useful? 

https://github.com/ngx-universal/transfer-state
