### ISSUE TITLE
Implementing a service worker

### ISSUE THREAD

**Issue by Twisterking** [evertonrobertoauler/cli-universal-demo#13]
Thanks a bunch for this awesome little boilerplate! It is the only really maintained an actually working one out there ... I think! Great work!
I would like to build a Angular2 PWA (progressive web app) including SSR with express ... are there any plans from your side or maybe some tips you can give me on how to include something like [mobile.angular.io Service Worker](https://github.com/angular/mobile-toolkit/tree/master/service-worker) and have it working properly?!
Or is this service worker boilerplate maybe over the top and I just need something caching .js, .css and image files and that's pretty much it?!

**Comment by evertonrobertoauler** [comment]
I'm building a simple and lite boilerplate, using just webpack, with AOT:

https://github.com/evertonrobertoauler/universal-demo

I'm planning on add service worker in that project soon.
