### ISSUE TITLE
angular page start with server side argument.

### ISSUE THREAD

**Issue by xkguq007** [evertonrobertoauler/cli-universal-demo#15]
first of all, sorry for my bad english.

I don't know how can i pass server side argument.

for example,

app.get('/foo', (req, res) => {
  res.render('index', { req, testArg: 'hi' });
});

and, client side,

<p>
  home-page works! <%= testArg %>
</p>

like this.

why am i doing this is my title and sns value is dynamically changed what pk is.
my url sample is localhost/items/:itemPk

and title and sns value is changed (for SEO) depends on itemPk.

I wish you can understand what I'm talking about.

**Comment by evertonrobertoauler** [comment]
Instead of passing this information from the server, you can use the Title and Meta services to set the title or meta tags, like the example bellow.

https://github.com/evertonrobertoauler/cli-universal-demo/blob/master/src/app/app.component.ts

It work using server side rendering too.

**Comment by xkguq007** [comment]
thanks for your reply,
but is it work with web crawler that does not support spa??
google web crawler support spa however, NAVER which is web site in korea, its web crawler doesn't support spa.

**Comment by evertonrobertoauler** [comment]
It work with web crawler, because the title will be rendered in the server.
run the following commands:

git clone https://github.com/evertonrobertoauler/cli-universal-demo.git
cd cli-universal-demo
npm install
npm run start
open http://localhost:4000

disable javascript, you will see that the title and meta tags are rendered in the server by renderModuleFactory.

**Comment by evertonrobertoauler** [comment]
Or add a console log in src/server.ts

  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => {
      console.log(html);
      callback(null, html);
});

**Comment by xkguq007** [comment]
wow, i can't think to test with disable javascript.
Interesting. this is the greatest demo project with angular4 universal.
I wish I can help this project sometime.
I will change my backend skeleton to based on this demo. thanks again.

**Comment by evertonrobertoauler** [comment]
I'm building a more simple and lite boilerplate, using just webpack, with AOT,
try this project, and if you'd like to help, let me know.

https://github.com/evertonrobertoauler/universal-demo
