### ISSUE TITLE
Adding app.browser.module

### ISSUE THREAD

**Issue by yamidvo** [evertonrobertoauler/cli-universal-demo#17]
Hello and thank you, I need to add the file app.browser.module to handle some dependencies in another way, for example:  I need to handle the cookie service separately, one service in the browser and another in the server.

**Comment by evertonrobertoauler** [comment]
You can create a app.browser.module.ts, and in the main.ts file, instead of importing app.module.ts, you can import app.browser.module.ts

And I believe that everything will work just fine.

**Comment by evertonrobertoauler** [comment]
I tried to implement this, but it didn't work.
