### ISSUE TITLE
canonical link href server side rendering 

### ISSUE THREAD

**Issue by TroodoNmike** [evertonrobertoauler/cli-universal-demo#18]
Hello,

I am using this repo (thanks for creating it) and I wonder if anyone solved problem around rendering <link rel="canonical" href="/link/here"> tag in head.

I can use Title and Meta service to update information in the head but <link> cannot be accessed. Any ideas?

**Comment by evertonrobertoauler** [comment]
Unfortunately, I believe the only 2 services implemented yet to update the head information is the Title and Meta services

https://angular.io/api/platform-browser

This issue shows an alternative way, of how you can do this for now:

https://github.com/angular/angular/issues/15776
