### ISSUE TITLE
Is there any way to use angular-cli to generate components

### ISSUE THREAD

**Issue by linux-nerd** [evertonrobertoauler/cli-universal-demo#20]
Is there any way to use angular-cli to generate components. I tried using 

`./node_modules/.bin/ng generate component contact`
But it errors out 

> 

    installing component
    Error locating module for declaration
    SilentError: Multiple module files found:

I kind of get it that the cli needs to be exited but is there any workaround for this?

**Comment by gags88** [comment]
Hi Linux-nerd..

you can use 

ng g c home --module=app.module.ts

**Comment by linux-nerd** [comment]
@gags88 Thanks :+1:

**Comment by TroodoNmike** [comment]
Thats really useful!  I would recommend to put this on the readme on this repo
