### ISSUE TITLE
Is there any way to use cookie values in the server?

### ISSUE THREAD

**Issue by adebree** [evertonrobertoauler/cli-universal-demo#21]
Thanks for your example repo! Really helpful. I do encounter a challenge with reading cookie data. How to get the cookie value from the request? renderModuleFactory or Express itself doesn't seem to inject it.

**Comment by TroodoNmike** [comment]
I use ngx-cookie package and whenever I need to use cookie data I have to use isBrowser property. Here is an example:

```
import { isPlatformBrowser } from '@angular/common';
import { PLATFORM_ID } from '@angular/core';

```
    public isBrowser: boolean = isPlatformBrowser(this.platformId);

    // component constructor
    constructor(@Inject(PLATFORM_ID) private platformId, private cookieService: CookieService) {}


        if (this.isBrowser) {
            let name = cookieService.get('name');
        }

**Comment by evertonrobertoauler** [comment]
You can use this library, https://www.npmjs.com/package/universal-cookie

**Comment by webdeveloperneeraj** [comment]
constructor(private http: Http, @Inject(PLATFORM_ID) private readonly platformId: any) {
     this.originUrl = this._utils.ORIGIN_URL;
        console.log(isPlatformBrowser(this.platformId))
      if(isPlatformBrowser(this.platformId) ) {
        this.originUrl = window.location.origin;
     }
  }
It's not working for me i am getting false in console.
