### ISSUE TITLE
Home Page does not load after adding ngb-carousel

### ISSUE THREAD

**Issue by sahil-developer-88** [evertonrobertoauler/cli-universal-demo#22]
Here is my **angular-cli-json**:
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "cli-universal-demo"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/tether/dist/js/tether.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
}

And here is **webpack.config.js** :

const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: {
    server: './src/server.ts'
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
  target: 'node',
   externals: [nodeExternals({
     whitelist: [

       /^@ng-bootstrap\/ng-bootstrap/
     ]
   })],
  node: {
    __dirname: true
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  module: {
    rules: [
      { test: /\.ts$/, loader: 'ts-loader' }
    ]
  }
}

I also added the sass file for bootstrap in styles.sass
Home Page does not load after adding ngb-carousel. But it works if we route through button click. Also the bootstrap does not work for navigation bar

**Comment by ysus** [comment]
https://embed.plnkr.co/ScE0uqfd0ZvL6T9j1XjL/ this work fine with angular universal

**Comment by sahil-developer-88** [comment]
Thanks for your response. But I am getting issue with ngb-carousel (ng-bootstrap). That doesn't let the page to load if I put direct url in address bar for the page containing ngb-carousel. But if i navigate through router  then the same page loads. Please help me out to know where the issue could be. 
Thank you.

**Comment by ysus** [comment]
angular universal not support 100% ng-bootstrap i think.
are you using the ng-bootstrap branch?

if you say tha the problem is when you try to load the page  direct in address bar  is because the setinterval  that use the ngb-carousel.
https://github.com/valor-software/ngx-bootstrap/issues/1353

whe you use the click button the page was loaded in the browser.

**Comment by sahil-developer-88** [comment]
Yes I used ng-bootstrap branch. Here is my code how I used ngb-carousel:
Html:
Plz see the attached file for html file.
[home.component.txt](https://github.com/evertonrobertoauler/cli-universal-demo/files/1100487/home.component.txt)

.ts file:
[home.component.ts.txt](https://github.com/evertonrobertoauler/cli-universal-demo/files/1100488/home.component.ts.txt)


Please tell me how i can set timeout for this kind of implementation of ngb-carousel.

**Comment by ysus** [comment]
your files are ok, the problem is the setinterval that containt the ngb-carousel.ts you need to changed like this issue
https://github.com/valor-software/ngx-bootstrap/issues/1353

**Comment by sahil-developer-88** [comment]
ok, thanks for your quick reply, I will look into it. In future, if you get any updates regarding this issue, you can please let me know .
