### ISSUE TITLE
listen in 0.0.0.0

### ISSUE THREAD

**Issue by danvelcab** [evertonrobertoauler/cli-universal-demo#26]
Hi. I changed the file sever.js to listen in 0.0.0.0 but I can not get it to work. Can anybody help me.
This is the code?:

<pre>
app.listen(PORT, "0.0.0.0" () => {
  console.log(`listening on http://localhost:${PORT}!`);
});
</pre>

Thanks

**Comment by evertonrobertoauler** [comment]
Hi, It could be your firewall that is blocking the PORT access for other machines in your local network, I use the following code:
`app.listen(PORT, () => { console.log(`listening on http://localhost:${PORT}!`); });`
And it works fine, I can access my app from my smartphone in the same network without the need of passing 0.0.0.0 as the second listen parameter

**Comment by danvelcab** [comment]
I'm sorry. Thanks you for the repply but it was a problems with ports.
