### ISSUE TITLE
language change print out in html

### ISSUE THREAD

**Issue by chriseugenerodriguez** [evertonrobertoauler/cli-universal-demo#27]
@evertonrobertoauler really appreciate you helping me on translation issue, anyway I have language print out in html when I change language?

**Comment by evertonrobertoauler** [comment]
yes, but it prints the default language, that is 'en'

you can get the user language on the server with the accept-language header, just change the server.ts and app.component.ts as the following gists:

https://gist.github.com/evertonrobertoauler/20c572bf6f49123dc3debabeba097e44

https://gist.github.com/evertonrobertoauler/3c208d3f2bf7bf68748eb569f58bed79

![screenshot from 2017-07-14 22-07-35](https://user-images.githubusercontent.com/4536606/28235274-df98ff6e-68e0-11e7-9328-c861c1d97461.png)

**Comment by chriseugenerodriguez** [comment]
@evertonrobertoauler hey thanks for this info. I managed to change these two files, but no luck. I added it to repo too if you could check.

**Comment by evertonrobertoauler** [comment]
@premiumwd here it is working just fine, i didn't change any file, I cloned your repo as it is right now.

0948fd5 (HEAD -> master, origin/master, origin/HEAD) server side translations change

![screenshot from 2017-07-15 00-40-12](https://user-images.githubusercontent.com/4536606/28236209-3d19175e-68f6-11e7-9d31-b7b738cd1f2c.png)

**Comment by chriseugenerodriguez** [comment]
@evertonrobertoauler so did you load it initially in spanish, or did you use dropdown and change language? I used dropdown to change language. How did you change language and get it to print out initially? I am changing language with dropdown and viewing source. Thanks a lot for your help bro.

**Comment by evertonrobertoauler** [comment]
It did load initially in `pt` because in the server code I'm getting the accept-language header that the browser sends with the request.
I didn't need to use the use the dropdown.

**Comment by chriseugenerodriguez** [comment]
how did you load it initially in pt?
