### ISSUE TITLE
Deploying the universal app

### ISSUE THREAD

**Issue by Harsh19397** [evertonrobertoauler/cli-universal-demo#29]
I am facing issues in running the server.js file listed in dist folder even after installing all the required packages I am getting the following error
![screenshot from 2017-07-19 11-37-37](https://user-images.githubusercontent.com/24836614/28352907-b06f6ebe-6c76-11e7-9e8a-fbcd645e93c2.png)

**Comment by evertonrobertoauler** [comment]
Hi
Run server.js from the project root folder.
`node dist/server.js`
