### ISSUE TITLE
core+common+http

### ISSUE THREAD

**Issue by jlar33** [evertonrobertoauler/cli-universal-demo#3]
help me please I want to use Angular 4+ Angular universal +Angular material,
I have this when I run "npm install" on a clone of your repository:
![image](https://cloud.githubusercontent.com/assets/26155404/24567833/f266925a-1624-11e7-8f89-920b792b977b.png)

and when I run "npm run start", I have this:
![image](https://cloud.githubusercontent.com/assets/26155404/24568747/c4a5e182-1628-11e7-8f33-ebb31c7fef33.png)

But it works. I will have problems because of those errors?

**Comment by evertonrobertoauler** [comment]
Take a look on my last commit, I added the webpack-node-externals module, and configured it in the webpack.config.js, to not bundle the files from node_modules with in the server.js file. 

Now there is no warnings and I added a gulpfile, to transpile the sass code into css before running the ngc command. 

Update your repo and take a look
