### ISSUE TITLE
Meta Tags not working

### ISSUE THREAD

**Issue by KrGyan** [evertonrobertoauler/cli-universal-demo#31]
//Imported 

import { Meta, Title } from '';

//DI:
private seoServiceObj: Meta

//Meta :
this.seoServiceObj.updateTag({name:'description',content : data.info.meta_desc});
this.seoServiceObj.updateTag({name:'publish-date',content : data.info.published_date1});
this.seoServiceObj.updateTag({name:'modified-date',content : data.info.published_date1});

Issue::
The meta are updated on client side while they are not updated on SSR.

**Comment by KrGyan** [comment]
Basically , I reviewed it and saw that on any page it renders HTML for Home Page only. That is real headache

**Comment by evertonrobertoauler** [comment]
The Meta and Title services work, clone this repo, and run npm install && npm run start, debug the network requests or disable javascript, you will see that the meta tags come updated from the server.

You are doing something wrong in your project, did you add this meta tags on your index.html before trying to update them in your code?

**Comment by KrGyan** [comment]
Thanks... It was issue with script.
