### ISSUE TITLE
ERROR ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by fifths** [evertonrobertoauler/cli-universal-demo#34]
I get this error when trying to use the localStorage

**Comment by evertonrobertoauler** [comment]
Hi

localStorage does not exist on the server, you need to test which platform you are running before use localStorage, you can only use local storage on the browser, look the following example:

https://gist.github.com/evertonrobertoauler/aed3f2f50694c524d880ad1a5c5838f7

**Comment by fifths** [comment]
@evertonrobertoauler  thanks
