### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by Maciekek** [evertonrobertoauler/cli-universal-demo#6]
Hello, great example of server side rendering! 
I have a question about development mode. Angular cli has sth like `ng build -op dist -w` to watch changes in code. In your code it is not working because this is not reloding server side. Do you know how it should work? Or do you have some command for this? 

Thanks in advance

**Comment by evertonrobertoauler** [comment]
I'm using ng serve in JIT mode for development, I'm testing the server part only a few times before deployment, to make sure everything works as expected rendering in the server too.
But yes, it would be really nice if we could develop with watch mode, using SSR as default, but unfortunately, the @angular/compiler-cli does not have a watch parameter yet, we could create a gulp task, to watch for changes and rebuild and restart the server every time something change, but it would consume a lot of machine resources and time.
I heard from the angular-cli team at ng-conf that the first priority they have right now is to improve the @angular/compiler-cli project adding watch mode, but I think this will take 1 or 2 months to be available.

**Comment by Maciekek** [comment]
`ng-serve` is good enough for me, thanks for help:)
