### ISSUE TITLE
BrowserAnimationsModule and @angular/material

### ISSUE THREAD

**Issue by thePunderWoman** [evertonrobertoauler/cli-universal-demo#8]
This repo is exactly what I needed. Thanks for your work! One issue I've hit is that using your @angular/material branch as an example, I've gotten things working pretty well. However, as soon as I add in BrowserAnimationsModule that is required with @angular/material beta.3, the server just hangs and never loads the page. You can reproduce this in your own repo by just going into app.module.ts, adding the import line `import { BrowserAnimationsModule } from '@angular/platform-browser/animations';` and the adding the module as an import. Do you know of a way to conditionally add this dependency only on the client side? I've had no luck so far.

**Comment by ysus** [comment]
hello, can you fix the problem?

**Comment by pquarme** [comment]
Finally found a working solution for this problem. I'll create a fork if people still need it. Let me know.

**Comment by ysus** [comment]
can you shared the repo pleasee!!

**Comment by pquarme** [comment]
Here -> https://github.com/pquarme/cli-universal-demo
Readme should have everything added and changed

**Comment by ysus** [comment]
aweson!! thnk so much @pquarme, i think  that @janiukjf  should close the issue

**Comment by thePunderWoman** [comment]
I need to buy @pquarme a beer! Nice job, @pquarme!
