### ISSUE TITLE
@angular/material branch not working 

### ISSUE THREAD

**Issue by ysus** [evertonrobertoauler/cli-universal-demo#9]
hello, thanks for sharing the repo is faboulus.
but i have a problem with the @angular/material repo, it is working fine with ng serve, but when i run with npm run start is not working 

ERROR { ReferenceError: document is not defined

thanksss!

**Comment by evertonrobertoauler** [comment]
Unfortunately the angular/material does not fully support Server Side Rendering, some components like md-toolbar work, but some like md-button does not.
